version: "3.8"

networks:
  dev:
    driver: bridge

volumes:
  postgres-data:
    driver: local
  minio-data:
    driver: local

services:
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - 80:80
      - 443:443
    volumes:
      - .nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    depends_on:
      - frontend
      - mydarkhobby
    networks:
      - dev

  frontend:
    build:
      context: .
      dockerfile: Dockerfile
      target: frontend
    container_name: frontend
    expose:
      - 443
    environment:
      - VITE_PUBLIC_CDN_URL=${VITE_PUBLIC_CDN_URL}
      - VITE_APP_NAME=${VITE_APP_NAME}
      - VITE_MEDIA_FACEBOOK=${VITE_MEDIA_FACEBOOK}
      - VITE_MEDIA_INSTAGRAM=${VITE_MEDIA_INSTAGRAM}
      - VITE_MEDIA_TWITTER=${VITE_MEDIA_TWITTER}
      - VITE_MEDIA_TELEGRAM=${VITE_MEDIA_TELEGRAM}
    networks:
      - dev

  mydarkhobby:
    build:
      context: ../mydarkhobby
      dockerfile: Dockerfile
      target: mydarkhobby
    container_name: mydarkhobby
    #    expose:
    #      - 443
    #      - 4321
    ports:
      - 4321:443
    networks:
      - dev

  backend:
    build:
      context: .
      dockerfile: Dockerfile
      target: backend
    container_name: backend
    ports:
      - 4000:4000
    environment:
      - DB_CONNECTION_URI=${DB_CONNECTION_URI}
      - MINIO_ENDPOINT=${MINIO_ENDPOINT}
      - MINIO_ACCESS_KEY=${MINIO_ACCESS_KEY}
      - MINIO_SECRET_KEY=${MINIO_SECRET_KEY}
      - MINIO_BUCKET=${MINIO_BUCKET}
      - MINIO_REGION=${MINIO_REGION}
      - APP_EMAIL_ADDRESS=${APP_EMAIL_ADDRESS}
      - APP_EMAIL_PASSWORD=${APP_EMAIL_PASSWORD}
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - SESSION_SECRET=${SESSION_SECRET}
      - ACCESS_TOKEN_SECRET=${ACCESS_TOKEN_SECRET}
      - REFRESH_TOKEN_SECRET=${REFRESH_TOKEN_SECRET}
      - CLIENT_URL=${CLIENT_URL}
      - ADMIN_EMAILS=${ADMIN_EMAILS}
    depends_on:
      - postgres
    networks:
      - dev

  postgres:
    image: postgis/postgis:14-3.4-alpine
    container_name: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - dev

  minio:
    image: quay.io/minio/minio
    container_name: minio
    command: server /data --console-address ":9090"
    restart: always
    ports:
      - 9000:9000
      - 9090:9090
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
      MINIO_SERVER_HOST: minio.altloc.com
      MINIO_BROWSER_REDIRECT_URL: http://minio.altloc.com
      MINIO_SERVER_URL: http://minio.altloc.com
    volumes:
      - minio-data:/data
    networks:
      - dev

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    entrypoint:
      [
        "/bin/sh",
        "-c",
        "trap 'exit 0' TERM; while :; do sleep 6h & wait $!; certbot renew --non-interactive; done",
      ]
    command: certonly --webroot -w /var/www/certbot --force-renewal \
      --non-interactive --email progof031@gmail.com \
      -d altloc.com -d www.altloc.com \
      -d mydarkhobby.com -d www.mydarkhobby.com --agree-tos
    networks:
      - dev
