version: "3.9"

services:
  postgres:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: cyberlive
      POSTGRES_PASSWORD: cyberlive
      POSTGRES_DB: cyberlive
